### ISSUE TITLE
GraphiteReporter cannot recover from lost connection

### ISSUE THREAD

**Issue by jwhitlark** [sjl/metrics-clojure#63]
It looks like a network hiccup can cause GraphiteReporter to get into a bad state.  I can consistently get the following pair of errors (which constantly repeat) by interrupting the network connection.  I don't see a bug report upstream in dropwizard/metrics, but I'm not sure if this is a problem with metrics-clojure or dropwizard/metrics.

    2015-02-17 14:18:53,562 WARN  com.codahale.metrics.graphite.GraphiteReporter: Unable to report to Graphite
    java.net.SocketException: Broken pipe
            at java.net.SocketOutputStream.socketWrite0(Native Method)
            at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
            at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
            at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
            at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
            at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
            at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
            at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
            at java.io.BufferedWriter.write(BufferedWriter.java:230)
            at java.io.Writer.write(Writer.java:157)
            at com.codahale.metrics.graphite.Graphite.send(Graphite.java:130)
            at com.codahale.metrics.graphite.GraphiteReporter.reportMetered(GraphiteReporter.java:234)
            at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:170)
            at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162)
            at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
            at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)
    2015-02-17 14:18:53,562 WARN  com.codahale.metrics.graphite.GraphiteReporter: Error closing Graphite
    java.net.SocketException: Broken pipe
            at java.net.SocketOutputStream.socketWrite0(Native Method)
            at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
            at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
            at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
            at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
            at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
            at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
            at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
            at java.io.BufferedWriter.write(BufferedWriter.java:230)
            at java.io.Writer.write(Writer.java:157)
            at com.codahale.metrics.graphite.Graphite.send(Graphite.java:130)
            at com.codahale.metrics.graphite.GraphiteReporter.reportMetered(GraphiteReporter.java:234)
            at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:170)
            at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162)
            at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
            at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)

**Comment by jwhitlark** [comment]
Perhaps it's https://github.com/dropwizard/metrics/issues/694 ?

**Comment by michaelklishin** [comment]
@jwhitlark this is something that has to be fixed in Metrics, not this project.

**Comment by jwhitlark** [comment]
For future reference, dropwizard/metrics has a merged fix (as of Oct. 24, 2014).  According to their tickets, it should be part of their 3.1.1 release, although I don't see an ETA, and that was almost 4 months ago.
